"""empty message

Revision ID: 503fcbf24db0
Revises: 6ab7de67bc32
Create Date: 2023-02-20 17:55:22.096899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503fcbf24db0'
down_revision = '6ab7de67bc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
